# Plugin params
solver_plugin: solver_plugins::CeresSolver
ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
ceres_preconditioner: SCHUR_JACOBI
ceres_trust_strategy: LEVENBERG_MARQUARDT
ceres_dogleg_type: TRADITIONAL_DOGLEG
ceres_loss_function: None

# ROS Parameters
odom_frame: odom
map_frame: map
base_frame: base_link
scan_topic: /scan
mode: localization  # CHANGED FROM 'mapping'

# Map loading
map_file_name: /home/ubuntu/catkin_ws/src/my_robot/maps/my_map
map_start_pose: [0.0, 0.0, 0.0]

# Solver Parameters
map_update_interval: 2.0
resolution: 0.05
max_laser_range: 12.0
minimum_time_interval: 0.5
transform_publish_period: 0.02
tf_buffer_duration: 30.0
stack_size_to_use: 40000000
enable_interactive_mode: false  # CHANGED

# General Parameters
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.2
minimum_travel_heading: 0.2
scan_buffer_size: 10
scan_buffer_maximum_scan_distance: 10.0
link_match_minimum_response_fine: 0.1
link_scan_maximum_distance: 1.5

# NO loop closure in localization mode
do_loop_closing: false
